# Superstore Dataset — Data Exploration & Cleaning with Pandas

**Objective:** Learn Python basics and perform data exploration and cleaning using Pandas.

**Dataset:** Superstore Sales dataset (Kaggle: `vivek468/superstore-dataset-final`).

> Note: This notebook was built in a sandboxed environment without access to Kaggle, so it ships with
> `data/superstore_raw.csv`, a synthetic dataset that mirrors the real Superstore schema (same column
> types, plus intentionally injected missing values and duplicate rows so every cleaning step below has
> something real to do). To use the actual Kaggle data, download it from the link above, place it at
> `data/superstore_raw.csv` (or update the path below), and re-run all cells — the pipeline is identical.

**Steps covered:**
1. Load CSV into a DataFrame
2. Explore the data (head/tail, shape, columns, dtypes)
3. Handle missing values
4. Basic operations (filter rows, select columns)
5. Remove duplicates
6. Create a derived column (`total_amount = price * quantity`)
7. Save the cleaned dataset to a new CSV

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

## 1. Load the CSV dataset into a Pandas DataFrame

In [2]:
DATA_PATH = "../data/superstore_raw.csv"

df = pd.read_csv(DATA_PATH)
print(f"Loaded {len(df)} rows and {len(df.columns)} columns")
df.head()

Loaded 520 rows and 16 columns

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,City,Category,Sub_Category,Product_Name,Price,Quantity,Discount
0,ORD-1001,2023-01-21,2023-01-23,First Class,CUST-0075,Customer 88,Consumer,South,Texas,Houston,Technology,Copiers,Copiers Model 971,475.60,8.0,0.0
1,ORD-1002,2024-02-18,2024-02-24,Same Day,CUST-0021,Customer 58,Corporate,East,New York,New York City,Technology,Machines,Machines Model 847,32.92,8.0,0.3
2,ORD-1003,2024-07-20,2024-07-24,Standard Class,CUST-0131,Customer 51,Home Office,East,Florida,Miami,Furniture,Chairs,Chairs Model 940,264.76,3.0,0.3
3,ORD-1004,2023-12-12,2023-12-17,Same Day,CUST-0092,Customer 111,Home Office,South,New York,New York City,Technology,Machines,Machines Model 608,474.70,2.0,0.1
4,ORD-1005,2024-01-23,2024-01-25,Second Class,CUST-0054,Customer 106,Corporate,East,Pennsylvania,Philadelphia,Technology,Accessories,Accessories Model 802,455.11,4.0,0.1

## 2. Explore the data

In [3]:
# First and last rows
df.head()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,City,Category,Sub_Category,Product_Name,Price,Quantity,Discount
0,ORD-1001,2023-01-21,2023-01-23,First Class,CUST-0075,Customer 88,Consumer,South,Texas,Houston,Technology,Copiers,Copiers Model 971,475.60,8.0,0.0
1,ORD-1002,2024-02-18,2024-02-24,Same Day,CUST-0021,Customer 58,Corporate,East,New York,New York City,Technology,Machines,Machines Model 847,32.92,8.0,0.3
2,ORD-1003,2024-07-20,2024-07-24,Standard Class,CUST-0131,Customer 51,Home Office,East,Florida,Miami,Furniture,Chairs,Chairs Model 940,264.76,3.0,0.3
3,ORD-1004,2023-12-12,2023-12-17,Same Day,CUST-0092,Customer 111,Home Office,South,New York,New York City,Technology,Machines,Machines Model 608,474.70,2.0,0.1
4,ORD-1005,2024-01-23,2024-01-25,Second Class,CUST-0054,Customer 106,Corporate,East,Pennsylvania,Philadelphia,Technology,Accessories,Accessories Model 802,455.11,4.0,0.1

In [4]:
df.tail()

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,City,Category,Sub_Category,Product_Name,Price,Quantity,Discount
515,ORD-1190,2024-06-23,2024-06-26,NaN,CUST-0005,Customer 5,Corporate,West,Texas,Houston,Technology,Copiers,Copiers Model 451,388.45,7.0,0.2
516,ORD-1435,2023-03-18,2023-03-22,Same Day,CUST-0039,Customer 12,Home Office,Central,California,Los Angeles,Office Supplies,Paper,Paper Model 538,58.48,7.0,0.2
517,ORD-1290,2023-12-27,2023-12-30,Second Class,CUST-0015,Customer 61,Corporate,East,Florida,Miami,Office Supplies,Paper,Paper Model 657,77.92,5.0,0.3
518,ORD-1143,2023-09-25,2023-09-28,Second Class,CUST-0040,Customer 21,Home Office,East,Illinois,Chicago,Office Supplies,Paper,Paper Model 966,496.11,6.0,0.0
519,ORD-1147,2023-05-13,2023-05-17,First Class,CUST-0001,Customer 57,Corporate,South,Florida,Miami,Office Supplies,Paper,Paper Model 383,227.14,9.0,0.0

In [5]:
# Shape: (rows, columns)
df.shape

(520, 16)

In [6]:
# Column names
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Ship_Date',
 'Ship_Mode',
 'Customer_ID',
 'Customer_Name',
 'Segment',
 'Region',
 'State',
 'City',
 'Category',
 'Sub_Category',
 'Product_Name',
 'Price',
 'Quantity',
 'Discount']

In [7]:
# Data types of each column
df.dtypes

Order_ID             str
Order_Date           str
Ship_Date            str
Ship_Mode            str
Customer_ID          str
Customer_Name        str
Segment              str
Region               str
State                str
City                 str
Category             str
Sub_Category         str
Product_Name         str
Price            float64
Quantity         float64
Discount         float64
dtype: object

In [8]:
# Summary info: dtypes, non-null counts, memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       520 non-null    str
 1   Order_Date     520 non-null    str
 2   Ship_Date      520 non-null    str
 3   Ship_Mode      504 non-null    str
 4   Customer_ID    520 non-null    str
 5   Customer_Name  505 non-null    str
 6   Segment        520 non-null    str
 7   Region         520 non-null    str
 8   State          520 non-null    str
 9   City           520 non-null    str
 10  Category       520 non-null    str
 11  Sub_Category   520 non-null    str
 12  Product_Name   520 non-null    str
 13  Price          505 non-null    float64
 14  Quantity       505 non-null    float64
 15  Discount       504 non-null    float64
dtypes: float64(3), str(13)
memory usage: 65.1 KB

In [9]:
# Quick statistical summary of numeric columns
df.describe()

            Price    Quantity    Discount
count  505.000000  505.000000  504.000000
mean   249.273842    4.976238    0.098413
std    145.803081    2.643394    0.116601
min      5.670000    1.000000    0.000000
25%    124.140000    3.000000    0.000000
50%    261.050000    5.000000    0.000000
75%    369.520000    7.000000    0.200000
max    499.180000    9.000000    0.300000

## 3. Handle missing values

In [10]:
# Identify missing values per column
missing_counts = df.isnull().sum()
missing_pct = (df.isnull().mean() * 100).round(2)
missing_summary = pd.DataFrame({"missing_count": missing_counts, "missing_pct": missing_pct})
missing_summary[missing_summary["missing_count"] > 0].sort_values("missing_count", ascending=False)

               missing_count  missing_pct
Ship_Mode                 16         3.08
Discount                  16         3.08
Customer_Name             15         2.88
Price                     15         2.88
Quantity                  15         2.88

In [11]:
# Strategy:
# - Numeric columns (Price, Quantity, Discount): fill with the column median
# - Categorical columns (Ship_Mode, Customer_Name): fill with a placeholder / mode

df_clean = df.copy()

numeric_fill_cols = ["Price", "Quantity", "Discount"]
for col in numeric_fill_cols:
    median_val = df_clean[col].median()
    df_clean[col] = df_clean[col].fillna(median_val)
    print(f"Filled missing {col} with median: {median_val}")

categorical_fill_cols = ["Ship_Mode", "Customer_Name"]
for col in categorical_fill_cols:
    mode_val = df_clean[col].mode()[0]
    df_clean[col] = df_clean[col].fillna(mode_val)
    print(f"Filled missing {col} with mode: {mode_val}")

Filled missing Price with median: 261.05
Filled missing Quantity with median: 5.0
Filled missing Discount with median: 0.0
Filled missing Ship_Mode with mode: Same Day
Filled missing Customer_Name with mode: Customer 109

In [12]:
# Confirm no missing values remain in the columns we handled
df_clean[numeric_fill_cols + categorical_fill_cols].isnull().sum()

# If any row still has missing critical identifiers (e.g., Order_ID), it would be safer to drop it.
# Example (not needed here since Order_ID has no missing values):
# df_clean = df_clean.dropna(subset=["Order_ID"])
df_clean.isnull().sum().sum()  # total remaining missing values

np.int64(0)

## 4. Basic operations — filter rows & select columns

In [13]:
# Select a subset of columns
subset_cols = ["Order_ID", "Category", "Sub_Category", "Region", "Price", "Quantity"]
df_clean[subset_cols].head()

   Order_ID    Category Sub_Category Region   Price  Quantity
0  ORD-1001  Technology      Copiers  South  475.60       8.0
1  ORD-1002  Technology     Machines   East   32.92       8.0
2  ORD-1003   Furniture       Chairs   East  264.76       3.0
3  ORD-1004  Technology     Machines  South  474.70       2.0
4  ORD-1005  Technology  Accessories   East  455.11       4.0

In [14]:
# Filter rows: Technology orders with Price > 200
tech_high_value = df_clean[(df_clean["Category"] == "Technology") & (df_clean["Price"] > 200)]
print(f"{len(tech_high_value)} Technology orders with Price > 200")
tech_high_value[subset_cols].head()

105 Technology orders with Price > 200

    Order_ID    Category Sub_Category Region   Price  Quantity
0   ORD-1001  Technology      Copiers  South  475.60       8.0
3   ORD-1004  Technology     Machines  South  474.70       2.0
4   ORD-1005  Technology  Accessories   East  455.11       4.0
13  ORD-1014  Technology       Phones  South  244.99       1.0
18  ORD-1019  Technology      Copiers  South  368.93       2.0

In [15]:
# Filter rows: orders shipped via Same Day
same_day = df_clean[df_clean["Ship_Mode"] == "Same Day"]
print(f"{len(same_day)} orders shipped Same Day")
same_day[["Order_ID", "Ship_Mode", "Region"]].head()

168 orders shipped Same Day

    Order_ID Ship_Mode   Region
1   ORD-1002  Same Day     East
3   ORD-1004  Same Day    South
5   ORD-1006  Same Day     East
9   ORD-1010  Same Day     East
10  ORD-1011  Same Day  Central

## 5. Remove duplicates

In [16]:
# Check for exact duplicate rows
dup_count = df_clean.duplicated().sum()
print(f"Duplicate rows found: {dup_count}")
df_clean[df_clean.duplicated(keep=False)].sort_values("Order_ID").head()

Duplicate rows found: 20

,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Region,State,City,Category,Sub_Category,Product_Name,Price,Quantity,Discount
31,ORD-1032,2023-05-07,2023-05-08,Standard Class,CUST-0129,Customer 58,Corporate,East,Washington,Seattle,Office Supplies,Paper,Paper Model 850,17.55,5.0,0.0
507,ORD-1032,2023-05-07,2023-05-08,Standard Class,CUST-0129,Customer 58,Corporate,East,Washington,Seattle,Office Supplies,Paper,Paper Model 850,17.55,5.0,0.0
47,ORD-1048,2024-01-04,2024-01-05,Standard Class,CUST-0117,Customer 134,Corporate,South,Florida,Miami,Technology,Phones,Phones Model 784,122.57,9.0,0.0
502,ORD-1048,2024-01-04,2024-01-05,Standard Class,CUST-0117,Customer 134,Corporate,South,Florida,Miami,Technology,Phones,Phones Model 784,122.57,9.0,0.0
66,ORD-1067,2023-08-19,2023-08-25,Second Class,CUST-0044,Customer 25,Consumer,East,New York,New York City,Furniture,Furnishings,Furnishings Model 311,14.94,9.0,0.0

In [17]:
# Drop duplicates, keeping the first occurrence
before = len(df_clean)
df_clean = df_clean.drop_duplicates(keep="first").reset_index(drop=True)
after = len(df_clean)
print(f"Removed {before - after} duplicate rows. New shape: {df_clean.shape}")

Removed 20 duplicate rows. New shape: (500, 16)

## 6. Create a derived column: `total_amount = price * quantity`

In [18]:
df_clean["total_amount"] = (df_clean["Price"] * df_clean["Quantity"]).round(2)
df_clean[["Order_ID", "Price", "Quantity", "total_amount"]].head()

   Order_ID   Price  Quantity  total_amount
0  ORD-1001  475.60       8.0       3804.80
1  ORD-1002   32.92       8.0        263.36
2  ORD-1003  264.76       3.0        794.28
3  ORD-1004  474.70       2.0        949.40
4  ORD-1005  455.11       4.0       1820.44

In [19]:
# Sanity check on the new column
df_clean["total_amount"].describe()

count     500.00000
mean     1241.53000
std      1015.04875
min        10.19000
25%       387.07500
50%       947.11000
75%      1913.73000
max      4476.33000
Name: total_amount, dtype: float64

## 7. Save the cleaned dataset as a new CSV

In [20]:
OUTPUT_PATH = "../data/superstore_cleaned.csv"
df_clean.to_csv(OUTPUT_PATH, index=False)
print(f"Saved cleaned dataset to {OUTPUT_PATH}")
print(f"Final shape: {df_clean.shape}")

Saved cleaned dataset to ../data/superstore_cleaned.csv
Final shape: (500, 17)

## Summary

- **Loaded** the raw Superstore CSV into a Pandas DataFrame and explored its shape, columns, and dtypes.
- **Missing values**: numeric columns (`Price`, `Quantity`, `Discount`) were filled with their median;
  categorical columns (`Ship_Mode`, `Customer_Name`) were filled with their mode.
- **Filtering**: demonstrated row filtering (e.g., high-value Technology orders, Same Day shipments) and
  column selection.
- **Duplicates**: identified and removed exact duplicate rows.
- **Derived column**: added `total_amount = Price * Quantity`.
- **Output**: saved the cleaned DataFrame to `data/superstore_cleaned.csv`.